name = "gk-minicode-pages"
pages_build_output_dir = "pages"
compatibility_date = "2024-07-14"

[vars]
SITE_DOMAIN = "https://gk.minicode.cloud"
HUPIJIA_APP_ID = "201906179658"

[[d1_databases]]
binding = "DB"
database_name = "gk-db"
database_id = "7e9e2bc1-cc6c-4889-8bcc-a697961559d4"